namespace FichaDigital.Api.Modules.Clientes.Application;

public sealed record DetalheClienteConsultado(
    Guid Id,
    string NomeReferencia,
    string? NomeCompleto,
    string? NomeSocial,
    string NomeParaExibicao,
    string? Pronomes,
    string? EstadoCivil,
    DateOnly? DataNascimento,
    string? Cpf,
    string? Celular,
    string? TelefoneAdicional,
    string? Email,
    string? Instagram,
    string? ContatoEmergenciaNome,
    string? ContatoEmergenciaCelular,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Estado,
    DateTimeOffset? DadosPessoaisPreenchidosEmUtc,
    DateTimeOffset CriadoEmUtc,
    IReadOnlyList<FichaClienteConsultada> Fichas);
