namespace FichaDigital.Api.Modules.Clientes.Api;

public sealed record ClienteDetalheResponse(
    Guid Id,
    string NomeReferencia,
    string? NomeCompleto,
    string? NomeSocial,
    string NomeParaExibicao,
    string? Pronomes,
    string? EstadoCivil,
    DateOnly? DataNascimento,
    string? Cpf,
    string? Celular,
    string? TelefoneAdicional,
    string? Email,
    string? Instagram,
    string? ContatoEmergenciaNome,
    string? ContatoEmergenciaCelular,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Estado,
    DateTimeOffset? DadosPessoaisPreenchidosEmUtc,
    DateTimeOffset CriadoEmUtc,
    IReadOnlyList<FichaClienteResumoResponse> Fichas);
