// <auto-generated />
using System;
using FichaDigital.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaDigital.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FichaDigitalDbContext))]
    [Migration("20260912234213_SimplifyStudioAccess")]
    partial class SimplifyStudioAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaDigital.Api.Infrastructure.Auditing.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CorrelacaoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OcorreuEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("Recurso", "RecursoId", "OcorreuEmUtc");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Infrastructure.Idempotency.RequisicaoIdempotente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("ConcluidaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorpoRespostaProtegido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ExpiraEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("TipoConteudo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEmUtc");

                    b.HasIndex("Escopo", "Chave")
                        .IsUnique();

                    b.ToTable("RequisicoesIdempotentes", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Clientes.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Celular")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContatoEmergenciaCelular")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DadosPessoaisPreenchidosEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeReferencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pronomes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefoneAdicional")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Celular");

                    b.HasIndex("Cpf");

                    b.HasIndex("NomeCompleto");

                    b.HasIndex("NomeReferencia");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.AceiteTermoConsentimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AceitoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AgenteUsuario")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AssinaturaDesenhada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmouLeituraEAutorizacao")
                        .HasColumnType("bit");

                    b.Property<string>("ConteudoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ConteudoTermo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ConviteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EvidenciaHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EvidenciaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeAssinante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VersaoEvidencia")
                        .HasColumnType("int");

                    b.Property<int>("VersaoTermo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConviteId");

                    b.HasIndex("FichaId")
                        .IsUnique();

                    b.ToTable("AceitesTermoConsentimento", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.ConviteFicha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiraEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ConvitesFicha", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.DadosPessoaisFicha", b =>
                {
                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ConfirmadosEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContatoEmergenciaCelular")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pronomes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefoneAdicional")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("FichaId");

                    b.ToTable("DadosPessoaisFichas", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.Ficha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CnpjApresentado")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ProfissionalResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfissionalResponsavelNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoProcedimento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("VersaoModelo")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoQuestionario")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoTermo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProfissionalResponsavelId");

                    b.HasIndex("Status");

                    b.HasIndex("TipoProcedimento");

                    b.ToTable("Fichas", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.QuestionarioSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ConsumiuBebidaAlcoolicaUltimas24Horas")
                        .HasColumnType("bit");

                    b.Property<string>("DescricaoAlergia")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DescricaoAnemia")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DescricaoDoencaTransmissivel")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DescricaoMedicacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EstaGravidaOuAmamentando")
                        .HasColumnType("bit");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Fuma")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiCondicaoCardiaca")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiDoencaTransmissivel")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiPressaoAlta")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("RespondidoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("TemAlergia")
                        .HasColumnType("bit");

                    b.Property<bool>("TemDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("TemEpilepsia")
                        .HasColumnType("bit");

                    b.Property<bool>("TemHemofilia")
                        .HasColumnType("bit");

                    b.Property<bool>("TeveAnemia")
                        .HasColumnType("bit");

                    b.Property<bool>("TeveHepatite")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDiabetes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoHepatite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UsaMarcaPasso")
                        .HasColumnType("bit");

                    b.Property<bool>("UsaMedicacao")
                        .HasColumnType("bit");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaId")
                        .IsUnique();

                    b.ToTable("QuestionariosSaude", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.RegistroPiercing", b =>
                {
                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgulhaUtilizada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssinaturaDesenhada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EvidenciaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JoiaUtilizada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocalPerfuracao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NomeProfissionalAssinante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfissionalNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("RegistradoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ValorSinal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("FichaId");

                    b.ToTable("RegistrosPiercing", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.RegistroTatuagem", b =>
                {
                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArteEfetivamenteTatuada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssinaturaDesenhada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EvidenciaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocalTatuagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MaterialUtilizado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NomeProfissionalAssinante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfissionalNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("RegistradoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ValorSinal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("FichaId");

                    b.ToTable("RegistrosTatuagem", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.RevisaoProfissional", b =>
                {
                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DadosDaFichaConferidos")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfissionalNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("RevisadaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FichaId");

                    b.ToTable("RevisoesProfissionais", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Profissionais.Domain.ProfissionalUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.AceiteTermoConsentimento", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.ConviteFicha", null)
                        .WithMany()
                        .HasForeignKey("ConviteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.AceiteTermoConsentimento", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.ConviteFicha", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.DadosPessoaisFicha", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.DadosPessoaisFicha", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.Ficha", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Clientes.Domain.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FichaDigital.Api.Modules.Profissionais.Domain.ProfissionalUsuario", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.QuestionarioSaude", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.QuestionarioSaude", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.RegistroPiercing", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.RegistroPiercing", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.RegistroTatuagem", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.RegistroTatuagem", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.RevisaoProfissional", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.RevisaoProfissional", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Profissionais.Domain.ProfissionalUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Profissionais.Domain.ProfissionalUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FichaDigital.Api.Modules.Profissionais.Domain.ProfissionalUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Profissionais.Domain.ProfissionalUsuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
