// <auto-generated />
using System;
using FichaDigital.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FichaDigital.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FichaDigitalDbContext))]
    [Migration("20260813143843_AddAceitesTermoConsentimento")]
    partial class AddAceitesTermoConsentimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FichaDigital.Api.Modules.Clientes.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Pronomes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Celular");

                    b.HasIndex("NomeCompleto");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.AceiteTermoConsentimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AceitoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConteudoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ConteudoTermo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeAssinante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VersaoTermo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaId")
                        .IsUnique();

                    b.ToTable("AceitesTermoConsentimento", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.ConviteFicha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiraEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ConvitesFicha", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.Ficha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Fichas", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.QuestionarioSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescricaoAlergia")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EstaGravidaOuAmamentando")
                        .HasColumnType("bit");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PossuiCondicaoCardiaca")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiPressaoAlta")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("RespondidoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("TemAlergia")
                        .HasColumnType("bit");

                    b.Property<bool>("TemDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("TemEpilepsia")
                        .HasColumnType("bit");

                    b.Property<bool>("TemHemofilia")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDiabetes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UsaMarcaPasso")
                        .HasColumnType("bit");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaId")
                        .IsUnique();

                    b.ToTable("QuestionariosSaude", (string)null);
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.AceiteTermoConsentimento", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.AceiteTermoConsentimento", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.ConviteFicha", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.Ficha", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Clientes.Domain.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FichaDigital.Api.Modules.Fichas.Domain.QuestionarioSaude", b =>
                {
                    b.HasOne("FichaDigital.Api.Modules.Fichas.Domain.Ficha", null)
                        .WithOne()
                        .HasForeignKey("FichaDigital.Api.Modules.Fichas.Domain.QuestionarioSaude", "FichaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
